- be/src/main/java/buddyguard/mybuddyguard/login/handler/CustomSuccessHandler.java
> [fix] 리다이렉트 URL 포트번호 변경

- be/src/main/java/buddyguard/mybuddyguard/login/handler/CustomSuccessHandler.java
> [fix] sameSite 임시설정

- be/src/main/java/buddyguard/mybuddyguard/config/CorsConfig.java
- be/src/main/java/buddyguard/mybuddyguard/login/handler/CustomSuccessHandler.java
전체 허용 말고 사이트 명시하도록 수정
#57
- Cors config 수정
> [fix] Cors config 수정

- be/ddl/hospital_records.sql
- be/src/main/java/buddyguard/mybuddyguard/hospital/controller/HospitalRecordController.java
- be/src/main/java/buddyguard/mybuddyguard/hospital/controller/reponse/HospitalRecordResponse.java
- be/src/main/java/buddyguard/mybuddyguard/hospital/controller/request/HospitalRecordCreateRequest.java
- be/src/main/java/buddyguard/mybuddyguard/hospital/controller/request/HospitalRecordUpdateRequest.java
- be/src/main/java/buddyguard/mybuddyguard/hospital/entity/HospitalRecord.java
- be/src/main/java/buddyguard/mybuddyguard/hospital/mapper/HospitalRecordMapper.java
- be/src/main/java/buddyguard/mybuddyguard/hospital/repository/HospitalRecordRepository.java
- be/src/main/java/buddyguard/mybuddyguard/hospital/service/HospitalRecordService.java
- be/src/test/java/buddyguard/mybuddyguard/hospital/service/HospitalRecordServiceTest.java
> [refactor]hospital 엔티티 수정 및 카테고리 추가 

- be/src/main/java/buddyguard/mybuddyguard/alert/service/FCMInitializer.java
> refactor: FCM 설정 application.yaml을 통해 되도록 변경 #37

- be/src/main/java/buddyguard/mybuddyguard/alert/service/FCMInitializer.java
> fix: 오류 수정 위한 커밋 #37

- be/src/main/java/buddyguard/mybuddyguard/hospital/controller/reponse/HospitalRecordResponse.java
- be/src/main/java/buddyguard/mybuddyguard/hospital/controller/request/HospitalRecordCreateRequest.java
- be/src/main/java/buddyguard/mybuddyguard/hospital/mapper/HospitalRecordMapper.java
- be/src/main/java/buddyguard/mybuddyguard/hospital/service/HospitalRecordService.java
- be/src/test/java/buddyguard/mybuddyguard/hospital/service/HospitalRecordServiceTest.java
> refactor: main category 추가 및 userId 삭제

- be/ddl/walk_records.sql
- be/src/main/java/buddyguard/mybuddyguard/s3/entity/S3Images.java
- be/src/main/java/buddyguard/mybuddyguard/walk/controller/WalkRecordController.java
- be/src/main/java/buddyguard/mybuddyguard/walk/controller/request/WalkRecordCreateRequest.java
- be/src/main/java/buddyguard/mybuddyguard/walk/controller/request/WalkRecordUpdateRequest.java
- be/src/main/java/buddyguard/mybuddyguard/walk/controller/response/WalkRecordResponse.java
- be/src/main/java/buddyguard/mybuddyguard/walk/entity/WalkRecord.java
- be/src/main/java/buddyguard/mybuddyguard/walk/mapper/WalkRecordMapper.java
- be/src/main/java/buddyguard/mybuddyguard/walk/repository/WalkRecordRepository.java
- be/src/main/java/buddyguard/mybuddyguard/walk/service/WalkRecordService.java
> Closes #38 
- walk CRUD
- petId 별 주간, 월간, 전체 요청 구현
> [FEAT] walk CRUD 작성

- be/src/main/java/buddyguard/mybuddyguard/walk/controller/WalkRecordController.java
- be/src/main/java/buddyguard/mybuddyguard/walk/controller/WalkRecordStatsController.java
- be/src/main/java/buddyguard/mybuddyguard/walk/controller/response/WalkRecordDetailResponse.java
- be/src/main/java/buddyguard/mybuddyguard/walk/controller/response/WalkRecordResponse.java
- be/src/main/java/buddyguard/mybuddyguard/walk/controller/response/WalkStatsWithRecordsResponse.java
- be/src/main/java/buddyguard/mybuddyguard/walk/mapper/WalkRecordMapper.java
- be/src/main/java/buddyguard/mybuddyguard/walk/service/WalkRecordService.java
- be/src/main/java/buddyguard/mybuddyguard/walk/service/WalkRecordStatsService.java
Fixes #38 
- 응답 값에 주간/월간 통계 기록 추가
- 주간/월간 기록 조회 service 와 controller를 기본  CRUD 와 구분하여 구현
> [FEAT] 주간/월간 기록 응답에 통계 기록 추가 

- be/ddl/walk_records.sql
- be/src/main/java/buddyguard/mybuddyguard/hospital/controller/HospitalRecordController.java
- be/src/main/java/buddyguard/mybuddyguard/walk/controller/WalkRecordController.java
- be/src/main/java/buddyguard/mybuddyguard/walk/controller/WalkRecordStatsController.java
- be/src/main/java/buddyguard/mybuddyguard/walk/controller/request/WalkRecordCreateRequest.java
- be/src/main/java/buddyguard/mybuddyguard/walk/controller/request/WalkRecordUpdateRequest.java
- be/src/main/java/buddyguard/mybuddyguard/walk/repository/WalkRecordRepository.java
- be/src/main/java/buddyguard/mybuddyguard/walk/service/WalkRecordService.java
- be/src/main/java/buddyguard/mybuddyguard/walk/service/WalkRecordStatsService.java
Fixes #38 
- ddl 수정
- 비즈니스 로직 컨트롤러에서 서비스로 이동
- @requiredargsconstructor 사용 추가 
- ceate 응답 ok -> creat로 변경
> [refactor] 산책 ddl 수정 및 코드 수정

- fe/src/helper/kakaoMapHelpers.ts
> test: 카카오맵 스크립트 콘솔확인

- fe/src/helper/kakaoMapHelpers.ts
> test: 다른 env값도 콘솔 확인

- be/src/main/java/buddyguard/mybuddyguard/invitation/controller/InvitationController.java
- be/src/main/java/buddyguard/mybuddyguard/jwt/controller/TokenController.java
- be/src/main/java/buddyguard/mybuddyguard/pet/contoller/PetController.java
Closes #88 
Pet, Token, Invitation 도메인들에 swagger api 설명을 추가했습니다.
> [feat] Pet, Token, Invitation swagger api 설명 추가

- be/src/main/java/buddyguard/mybuddyguard/hospital/controller/HospitalRecordController.java
- be/src/main/java/buddyguard/mybuddyguard/walk/controller/WalkRecordController.java
- be/src/main/java/buddyguard/mybuddyguard/walk/controller/WalkRecordStatsController.java
- be/src/main/java/buddyguard/mybuddyguard/walk/controller/response/WalkRecordResponse.java
Fixes #38 
- 컨트롤러에 스웨거 설명 추가
- WalkRecordRespons에   buddyIds  추가
> [refactor] swagger 설명 추 가 및 응답값 추가

- be/src/main/java/buddyguard/mybuddyguard/walk/controller/request/WalkRecordCreateRequest.java
- be/src/main/java/buddyguard/mybuddyguard/walk/controller/request/WalkRecordUpdateRequest.java
- be/src/main/java/buddyguard/mybuddyguard/walk/controller/response/WalkRecordResponse.java
- be/src/main/java/buddyguard/mybuddyguard/walk/entity/WalkRecord.java
- be/src/main/java/buddyguard/mybuddyguard/walk/mapper/WalkRecordMapper.java
- be/src/main/java/buddyguard/mybuddyguard/walk/util/JsonArrayConverter.java
Fixes #38 
-  buddyIds, centerPosition, path 의 request와  reponsens를 JsonArrayConverter를 사용하여  String 에서 List로 수정
> [refactor] Request, Response 응답 타입 수정

- be/src/main/java/buddyguard/mybuddyguard/walk/controller/request/WalkRecordCreateRequest.java
- be/src/main/java/buddyguard/mybuddyguard/walk/controller/request/WalkRecordUpdateRequest.java
- be/src/main/java/buddyguard/mybuddyguard/walk/controller/response/WalkRecordResponse.java
- be/src/main/java/buddyguard/mybuddyguard/walk/entity/WalkRecord.java
- be/src/main/java/buddyguard/mybuddyguard/walk/service/WalkRecordStatsService.java
- be/src/main/java/buddyguard/mybuddyguard/walk/util/JsonArrayConverter.java
Fixes #38 
- 반환 타입을 List<String>  으로 수정
- time은 반환타입을 LocalTime -> List<String> 으로 수정
- 조회날짜 기준으로 주간 데이터를 가지고 오도록 수정
> [refactor] 반환타입 수정 및 주간 조회 코드 수정

- fe/src/apis/walkAPI.ts
- fe/src/components/molecules/walk/ListBox.stories.tsx
- fe/src/components/molecules/walk/ListBox.tsx
- fe/src/components/organisms/walk/WalkList.tsx
- fe/src/components/organisms/walk/WalkModal.tsx
- fe/src/components/templates/ResponsiveLayout.tsx
- fe/src/hooks/useKakaoMap.ts
- fe/src/hooks/useWalkQuery.ts
> 실시간 현재 위치 경로 작업 테스트 

- fe/src/components/organisms/MyPageList.tsx
>
> Closes #이슈번호
> 로그아웃시 캐시 스토리지 삭제
>
> feat: 로그아웃시 캐시 스토리지 삭제

- fe/src/apis/walkAPI.ts
> header 컨텐츠 타입 명시

- fe/src/apis/walkAPI.ts
> style: 한줄띄기

- fe/src/apis/walkAPI.ts
- fe/src/components/organisms/walk/WalkModal.tsx
> refactor: 산책 등록 form수정

- be/ddl/user_tokens.sql
- be/src/main/java/buddyguard/mybuddyguard/alert/entity/RecordCreatedEvent.java
- be/src/main/java/buddyguard/mybuddyguard/alert/service/AlertEventListener.java
- be/src/main/java/buddyguard/mybuddyguard/alert/service/RecordCreationAspect.java
- be/src/main/java/buddyguard/mybuddyguard/weight/service/WeightService.java
#37 
AOP 적용
- 생성 작업을 트리거로 하여 모든 기록 (현재 코드에서는 체중, 병원 기록) 생성시 알림 전송 메서드가 실행 되는 기능 구현
> [알림기능] AOP 적용

- be/ddl/vaccination_records.sql
- be/src/main/java/buddyguard/mybuddyguard/vaccination/controller/VaccinationRecordController.java
- be/src/main/java/buddyguard/mybuddyguard/vaccination/controller/request/VaccinationCreateRequest.java
- be/src/main/java/buddyguard/mybuddyguard/vaccination/controller/request/VaccinationRecordCreateRequest.java
- be/src/main/java/buddyguard/mybuddyguard/vaccination/controller/request/VaccinationRecordUpdateRequest.java
- be/src/main/java/buddyguard/mybuddyguard/vaccination/controller/response/VaccinationRecordResponse.java
- be/src/main/java/buddyguard/mybuddyguard/vaccination/entity/VaccinationRecord.java
- be/src/main/java/buddyguard/mybuddyguard/vaccination/mapper/VaccinationRecordMapper.java
- be/src/main/java/buddyguard/mybuddyguard/vaccination/repository/VaccinationRecordRepository.java
- be/src/main/java/buddyguard/mybuddyguard/vaccination/service/VaccinationRecordService.java
- be/src/main/java/buddyguard/mybuddyguard/weight/contoller/WeightController.java
> [FEAT] 예방접종 CRUD 구현

- be/src/main/java/buddyguard/mybuddyguard/config/RedisConfig.java
> [refactor] 예방접종 리포지토리 설정에 추가 #120

- be/src/main/java/buddyguard/mybuddyguard/vaccination/entity/VaccinationRecord.java
#120 
예방접종 엔티티 필드에 해당하는 컬럼 명시적 추가
> [refactor] 예방접종 엔티티 필드에 해당하는 컬럼 명시적 추가

- fe/src/apis/walkAPI.ts
- fe/src/components/molecules/PeriodFilter.tsx
- fe/src/components/organisms/walk/WalkModal.tsx
- fe/src/hooks/useWalkQuery.ts
> 산책 등록시 mutation사용 및 성공,실패 의 경우 콜백함수 생성, 일반 버튼태그 사용

- fe/src/apis/walkAPI.ts
- fe/src/components/molecules/PeriodFilter.tsx
- fe/src/components/molecules/walk/WalkBuddySelectBar.tsx
- fe/src/components/molecules/walk/WalkFormItem.tsx
- fe/src/components/organisms/walk/WalkModal.stories.tsx
- fe/src/components/pages/walk/GoWalk.tsx
- fe/src/helper/kakaoMapHelpers.ts
- fe/src/hooks/useWalkQuery.ts
- fe/src/stores/usePetStore.ts
> 실제 버디 데이터로 산책 적용

- fe/src/components/pages/walk/Walk.tsx
> 실제 버디 데이터로 산책관리 - 조회 적용

- fe/src/components/molecules/walk/ListBox.stories.tsx
- fe/src/components/molecules/walk/ListBox.tsx
- fe/src/types/walk.ts
> refactor: 산책 상세데이터의 이미지 key값 변경 적용

- fe/package.json
- fe/pnpm-lock.yaml
- fe/src/components/organisms/walk/WalkModal.tsx
- fe/src/components/pages/my/AddBuddy.tsx
- fe/src/components/pages/my/MyBuddy.tsx
- fe/src/components/pages/walk/GoWalk.tsx
- fe/src/hooks/useFeedFormHandlers.ts
- fe/src/hooks/useHospitalFormHandlers.ts
- fe/src/hooks/useLoad.ts
- fe/src/hooks/useVaccinationFormHandlers.ts
- fe/src/stores/usePetStore.ts
> [fix] buddy 삭제 오류, alert 라이브러리 적용

- fe/src/components/pages/walk/GoWalk.tsx
> [FIX] 모바일에서 지도 안나오는 에러 수정

- be/ddl/walk_record_center_position.sql
- be/ddl/walk_record_path.sql
- be/src/main/java/buddyguard/mybuddyguard/walk/controller/request/WalkRecordCreateRequest.java
- be/src/main/java/buddyguard/mybuddyguard/walk/controller/request/WalkRecordUpdateRequest.java
- be/src/main/java/buddyguard/mybuddyguard/walk/entity/WalkRecord.java
- be/src/main/java/buddyguard/mybuddyguard/walk/entity/WalkRecordCenterPosition.java
- be/src/main/java/buddyguard/mybuddyguard/walk/entity/WalkRecordPath.java
- be/src/main/java/buddyguard/mybuddyguard/walk/repository/PetWalkRecordRepository.java
- be/src/main/java/buddyguard/mybuddyguard/walk/repository/WalkRecordPathRepository.java
- be/src/main/java/buddyguard/mybuddyguard/walk/service/WalkRecordService.java
- be/src/main/java/buddyguard/mybuddyguard/walkimage/service/WalkImageService.java
- be/src/main/java/buddyguard/mybuddyguard/walkimage/service/impl/WalkImageServiceImpl.java
Fixes #38 
1. WalkRecord 엔티티와 관련엔티티 연관관계 맵핑 수정
- PetWalkRecord에서 Cascade, orphanRemoval 삭제 후 repository생성하여 직접 추가
- WalkRecordPath에 walkrecord 컬럼 추가 후 @ManyToOne 설정, FK 설정
- WalkRecord에서 WalkRecordPath에 `mappedBy = "walkRecord"` 추가
2. ddl 수정
- WalkRecordCenterPositon 에서 walkRecord_id 컬럼 삭제
- WalkRecordCenterPositon에서 path_id 컬럼 삭제
3. CreateRequest 수정
- startDate, endDate를 String 에서 LocalDate로 수정한 후 ` @JsonFormat(pattern = "yyyy년 MM월 dd일")` 추가
- String은 Notnull -> Notblank 변경 
4.WalkRecordService 수정
- cascade를 사용하지 않으므로 직접 repository를 통해 저장하도록 수정
> [Refactor] Walk jpa 연관관계 및 ddl 수정

- be/src/main/java/buddyguard/mybuddyguard/walk/controller/WalkRecordController.java
- be/src/main/java/buddyguard/mybuddyguard/walk/controller/request/WalkRecordUpdateRequest.java
- be/src/main/java/buddyguard/mybuddyguard/walk/entity/WalkRecord.java
- be/src/main/java/buddyguard/mybuddyguard/walk/service/WalkRecordService.java
Fixes #38 
- 산책 기록 수정을 PUT -> PATCH로 변경
- startDate, endDate, endTime, totalTime, note, distance 만 수정 가능하도록 변경
- entity에 @DynamicUpdate 및 수정시 필요한 메서드 추가
- updateRequest에서  notnull, notblank 삭제
- request에서 엔티티 전체가 아닌 부분만 수정하도록 메서드 변경
- 위의 변경사항에 맞춰 service 로직 수정
> [refactor] update PUT -> PATCH로 변경

- be/src/main/java/buddyguard/mybuddyguard/exception/ImageFileRequiredException.java
- be/src/main/java/buddyguard/mybuddyguard/walk/controller/request/WalkRecordCreateRequest.java
- be/src/main/java/buddyguard/mybuddyguard/walk/controller/request/WalkRecordUpdateRequest.java
- be/src/main/java/buddyguard/mybuddyguard/walk/service/WalkRecordService.java
Fixes #38 
1. 이미지가 null 값이면 `ImageFileRequiredException`던지며 400에러가 나도록 수정
2. @JsonFormat 삭제 후 날짜 형식을 `2024-10-00` 으로 통일
3. toWalkRecord 메서드 createRequest에 생성 후 서비스에  적용
> [Refactor] 예외 처리 추가 및 @JsonFormat 삭제

- fe/src/components/molecules/Chart.tsx
- fe/src/components/molecules/PeriodFilter.tsx
- fe/src/components/molecules/walk/ListBox.tsx
- fe/src/components/organisms/walk/WalkCalendar.tsx
- fe/src/components/organisms/walk/WalkList.tsx
- fe/src/components/pages/walk/Walk.tsx
- fe/src/components/templates/ResponsiveLayout.tsx
> 모바일 환경에서 레이아웃 수정

- fe/src/components/pages/walk/Walk.tsx
> refactor: 빌드오류 수정

- fe/src/components/organisms/MyPageList.tsx
- fe/src/components/organisms/walk/WalkCalendar.tsx
- fe/src/components/pages/my/MyPage.tsx
> 산책 캘린더 이동 버그

- fe/src/components/molecules/PeriodFilter.tsx
- fe/src/components/organisms/walk/WalkCalendar.tsx
- fe/src/hooks/useWalkQuery.ts
> 산책 캘린더 수정 및 useQuery수정

- fe/src/components/organisms/BuddyInfoBar.tsx
> refactor: 모바일에서 background-image 안뜨는 이슈수정

- fe/src/components/molecules/Chart.tsx
- fe/src/components/organisms/walk/WalkList.tsx
- fe/src/components/pages/walk/Walk.tsx
> refactor: 전체에서 상세 모달 안뜨는 부분 수정

- fe/package.json
> chore: packageManager 버전 명시

- README.md
> docs: 리드미에 프론트 실행 명령어 수정

- fe/index.html
> feat: 디버깅 툴 index에 임시로 추가

- fe/index.html
> refactor: 배포 사이트에서도 확인하기위해 cdn방식으로변경

- fe/src/helper/drawHelpers.ts
- fe/src/helper/kakaoMapHelpers.ts
- fe/src/hooks/useKakaoMap.ts
> feat: 모바일에러 확인을 위한 콘솔로그들 추가

- fe/src/helper/drawHelpers.ts
- fe/src/helper/kakaoMapHelpers.ts
- fe/src/hooks/useKakaoMap.ts
- fe/src/utils/canvasUtils.ts
> refactor: 모바일에서 지도 에러 콘솔 추가 및 로직 변경 #153

- fe/src/components/pages/walk/WalkRefactor.tsx
> refactor: 이미지 그리는 부분이 문제인지 확인을 위해주석처리 #153

- fe/src/hooks/useKakaoMap.ts
> refactor: 이미지 그리는 로직에 문제 추적 콘솔 #153

- fe/src/hooks/useKakaoMap.ts
> refactor: linePath 저장 로직 문제 추적 콘솔 #153

- be/build.gradle
- be/src/main/java/buddyguard/mybuddyguard/config/SecurityConfig.java
Closes #176 
- 서버의 메트릭 데이터 모니터링을 위한 라이브러리 추가
- prometheus
- spring boot actuator
> [feat] 서버 메트릭 데이터 모니터링 기능 추가

- fe/src/components/organisms/walk/WalkModal.tsx
- fe/src/components/pages/walk/GoWalk.tsx
> Closes #178
message로 임계값과 경로 수 띄운 코드제거하여 원복
> 테스트 시 메세지 띄운것 원복 

- fe/src/components/pages/walk/GoWalk.tsx
- fe/src/hooks/walk/useKakaoMap.ts
- fe/src/hooks/walk/useKakaoMapInit.ts
- fe/src/hooks/walk/useWalkBuddys.ts
> 현재위치 못불러 왔을 때 에러 처리
